;;;; Symbols

(declare-file (indent enumeration 1))

(enumeration
  (id byte-order)
  (title "Byte order")
  (value (symbol big-endian)
         (title "Big endian (MSB first)"))
  (value (symbol little-endian)
         (title "Little endian (LSB first)")))

(enumeration
  (id architecture)
  (title "Computer architecture")
  (value (symbol aarch64)
         (alias arm64)
         (title "ARM 64-bit"))
  (value (symbol aarch64-be)
         (title "ARM 64-bit big-endian"))
  (value (symbol amd)
         (title "AMD brand CPUs"))
  (value (symbol arm32)
         (title "ARM 32-bit"))
  (value (symbol intel)
         (title "Intel brand CPUs"))
  (value (symbol ppc32)
         (title "PowerPC 32-bit"))
  (value (symbol x86)
         (title "Intel i386 and above"))
  (value (symbol x86-64)
         (title "AMD/Intel 64-bit")))

(enumeration
  (id language)
  (title "Programming language")
  (value (symbol common-lisp)
         (alias cl)
         (title "Common Lisp"))
  (value (symbol scheme)
         (title "Scheme"))
  (value (symbol r3rs)
         (title "Revised^3 Report on Scheme"))
  (value (symbol r4rs)
         (title "Revised^4 Report on Scheme"))
  (value (symbol r5rs)
         (title "Revised^5 Report on Scheme"))
  (value (symbol r6rs)
         (title "Revised^6 Report on Scheme"))
  (value (symbol r7rs)
         (title "Revised^7 Report on Scheme"))
  (value (symbol r7rs)
         (title "Revised^7 Report on Scheme"))
  (value (symbol r7rs-large)
         (title "Revised^7 Report on Scheme (large edition)")))

(enumeration
  (id os)
  (title "Operating system")
  (value (symbol unix)
         (title "Unix-like operating system"))
  (value (symbol bsd)
         (title "Berkeley Software Distribution-derived Unix OS")
         (parent unix))
  (value (symbol freebsd)
         (title "FreeBSD")
         (parent bsd))
  (value (symbol netbsd)
         (title "NetBSD")
         (parent bsd))
  (value (symbol openbsd)
         (title "OpenBSD")
         (parent bsd))
  (value (symbol dragonfly)
         (title "DragonFly BSD")
         (parent bsd))
  (value (symbol reactos)
         (title "ReactOS")
         (parent windows-nt))
  (value (symbol solaris)
         (title "The SunOS/Solaris family")
         (parent unix))
  (value (symbol windows)
         (title "The Windows operating system family"))
  (value (symbol windows-nt)
         (title "The Windows NT operating system family"))
  (value (symbol macos)
         (title "The Mac OS family"))
  (value (symbol macos-9)
         (title "The Mac OS X family"))
  (value (symbol macos-x)
         (title "The Mac OS X family")))

(enumeration
  (id kernel)
  (title "Operating system kernel")
  (value (symbol linux)
         (title "The Linux kernel"))
  (value (symbol freebsd)
         (title "The FreeBSD kernel"))
  (value (symbol windows-nt)
         (title "The Windows NT kernel"))
  (value (symbol reactos)
         (title "The ReactOS kernel"))
  (value (symbol haiku)
         (title "The Haiku BeOS-like kernel"))
  (value (symbol beos)
         (title "The original BeOS kernel")))

(enumeration
  (id pointer-model)
  (title "C pointer model")
  (value (symbol ilp32)
         (title "int, long and pointers 32 bits wide"))
  (value (symbol llp64)
         (title "int, long 32 and pointers 64 bits"))
  (value (symbol lp64)
         (title "int 32, long, pointers 64 bits wide")))

(enumeration
  (id common-lisp-implementation)
  (title "Common Lisp implementation")
  (value (symbol clisp)
         (title "GNU CLISP"))
  (value (symbol cmucl)
         (title "CMU Common Lisp"))
  (value (symbol ecl)
         (title "Embeddable Common Lisp (from KCL)"))
  (value (symbol ccl)
         (title " Clozure Common Lisp"))
  (value (symbol abcl)
         (title "Armed Bear Common Lisp"))
  (value (symbol sbcl)
         (title "Steel Bank Common Lisp"))
  (value (symbol sicl)
         (title "SICL"))
  (value (symbol mkcl)
         (title "ManKai Common Lisp (from ECL)")))

(enumeration
  (id scheme-implementation)
  (title "Scheme implementation")
  (value (symbol chezscheme)
         (title "Chez Scheme"))
  (value (symbol chibi)
         (title "Chibi-Scheme"))
  (value (symbol guile)
         (title "GNU Guile"))
  (value (symbol ikarus)
         (title "Ikarus Scheme"))
  (value (symbol fantastic)
         (title "(Fantastic Scheme, an example implementation)"))
  (value (symbol larceny)
         (title "Larceny"))
  (value (symbol s7)
         (title "S7 for Snd"))
  (value (symbol s9)
         (title "S9 (Scheme 9 from Empty Space)"))
  (value (symbol mzscheme)
         (title "MzScheme / PLT Scheme"))
  (value (symbol sagittarius)
         (title "Sagittarius"))
  (value (symbol vicare)
         (title "Vicare"))
  (value (symbol ypsilon)
         (title "Ypsilon")))

(enumeration
  (id lisp-implementation)
  (title "Lisp implementation")
  (value (symbol clojure)
         (title "The Clojure Lisp dialect"))
  (value (symbol clojurescript)
         (title "The ClojureScript Lisp dialect"))
  (value (symbol emacs)
         (title "The GNU Emacs text editor and Lisp system"))
  (value (symbol newlisp)
         (title "newLISP"))
  (value (symbol rep)
         (title "Rep")))
